const mutations = {
  CHANGE_POST: "CHANGE_POST",
  CHANGE_WEATHER: "CHANGE_WEATHER",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  ADD_SEARCH_HISTORY: "ADD_SEARCH_HISTORY",
  CITY_FORECAST: "CITY_FORECAST",
  GET_ERROR: "GET_ERROR",
};

export default mutations;
